### ISSUE TITLE
Repo? More like rip-off

### ISSUE THREAD

**Issue by its-the-shrimp** [CherniakYura/synapse.h#3]
Not only is this repo a blatant copy of https://github.com/tsoding/nn.h, it has erased the name of the original creator, violating the MIT license it's distributed with

**Comment by cherniaky** [comment]
Yes, I was not aware that it is violation of a license, so I will put it in place

**Comment by drocha87** [comment]
Maybe you don't know this feature: https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by cherniaky** [comment]
I like to do commit by commit like the original author

**Comment by drocha87** [comment]
So you literally copy the project line by line, change its name and not mention the original repo and author anywhere?

**Comment by cherniaky** [comment]
Yes, that was my mistake. I already added licenses of the original author to every repo i copied
